image: alpine:latest

pages:
  stage: deploy
  script:
  - mkdir public
  - mv website/index.html public
  - mv website/js public
  - mv website/css public
  - mv website/Data public
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - assignment3

