image: alpine:latest

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - index.html
    - Data
    - js
    - css
    expire_in: 1 day
  only:
  - assignment3

